name: Deploy typescript Branch to GitHub Pages

on:
  push:
    branches:
      - typescript
  workflow_dispatch:

# Berechtigungen für das GITHUB_TOKEN setzen
permissions:
  contents: read
  pages: write
  id-token: write

# Stellt sicher, dass nur ein Deployment gleichzeitig läuft
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run lint (CI)
        run: npm run lint:ci

      - name: Run typecheck
        run: npm run typecheck

      - name: Build project
        run: npm run build

      # Artifacts für GitHub Pages vorbereiten
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Der Ordner mit deinen fertigen Build-Dateien

      # Auf GitHub Pages veröffentlichen
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
